version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_app_1
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    volumes:
      - db_data:/var/lib/mysql  
    networks:
      - spring-boot-mysql-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: chandreyees20/docker-assignment
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs  # Bind mount to store logs on the host machine
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/docker_app_1
    networks:
      - spring-boot-mysql-network
      
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
    
networks:
  spring-boot-mysql-network:
    driver: bridge
    
volumes:
  db_data: